# Generated by Django 6.0.6 on 2026-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, default="fallback.png", upload_to=""),
                ),
                ("title", models.CharField(max_length=250)),
                ("content", models.TextField()),
                ("counted_views", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=False)),
                ("published_date", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
