# Generated by Django 6.0.6 on 2026-07-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default="fallback.png", upload_to="blog/"
            ),
        ),
    ]
